import turtle
from turtle import*
#José Javier Berreondo 1095324 / Diego Escobar 1084424
print("Preparate para leer este maravilloso cuento") 
nombre = input("¿Quién está leyendo el cuento? Ingresa tu nombre: ")
edad = int(input("¿Qué edad tienes? Ingresa tu edad: "))

if 0 > edad > 100:
    print("Ingrese una edad válida")
else:
    col = input("Escribe tu color preferido: \n1. 'Purple' \n2. 'Aquamarine' \n3. 'Blue' \n4. 'Salmon' \n5. 'Yellow' ")

#PARTE 1 HISTORIA
print ("En todos lados puede verse, toda la población está pendiente en sus televisores, están expectantes a un gran heroe, el Panda que los salvará a todos. El cohete está listo, el curso está establecido, la misión es clara y el heroe se despide de todos sus conocidos y familiares. El Panda salvador, universalmente conocido como " + nombre)
print ("será recordado en todo el mundo, en todos los mundos. El cohete enciende sus motores, la cuenta atrás termina y el salvador, abandona el planeta, que el amor de Dios este con él…")
turtle.speed(4000000)
turtle.shape('turtle')
turtle.title('PANDA ESTELAR')
turtle.teleport(-280,-250)
turtle.bgcolor('black')
turtle.begin_fill()
turtle.fillcolor('pink')
turtle.forward(550)
turtle.left(90)
turtle.forward(500)
turtle.left(90)
turtle.forward(550)
turtle.left(90)
turtle.forward(500)
turtle.left(90)
turtle.end_fill()
#Cara
turtle.penup()
turtle.left(90)
turtle.forward(250)
turtle.right(90)
turtle.forward(180)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor('white')
turtle.circle(100)
turtle.end_fill()
#Cuerpo 
turtle.pencolor('white')
turtle.penup()
turtle.right(90)
turtle.forward(190)
turtle.left(90)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor('white')
turtle.circle(120)
turtle.end_fill()
#Nariz
turtle.pencolor('black')
turtle.teleport(-105,70)
turtle.begin_fill()
turtle.fillcolor('gray')
turtle.forward(20)  
turtle.left(120)
turtle.forward(20)
turtle.left(120)
turtle.forward(20)
#Ojo negro izq
turtle.teleport(-170,120)
turtle.pencolor('black')
turtle.begin_fill()
turtle.fillcolor('gray')
turtle.circle(25)
turtle.end_fill()
#Ojo negro izq
turtle.teleport(-165,115)
turtle.pencolor('black')
turtle.begin_fill()
turtle.fillcolor('black')
turtle.circle(18)
turtle.end_fill()
#Pupila izq
turtle.teleport(-150,120)
turtle.pencolor('white')
turtle.begin_fill()
turtle.fillcolor('white')
turtle.circle(6)
turtle.end_fill()
#Ojo gris derecho
turtle.teleport(-70,120)
turtle.pencolor('black')
turtle.begin_fill()
turtle.fillcolor('gray')
turtle.circle(25)
turtle.end_fill()

#Ojo negro
turtle.teleport(-65,115)
turtle.pencolor('black')
turtle.begin_fill()
turtle.fillcolor('black')
turtle.circle(18)
turtle.end_fill()

#Pupila derecha
turtle.teleport(-50,120)
turtle.pencolor('white')
turtle.begin_fill()
turtle.fillcolor('white')
turtle.circle(6)
turtle.end_fill()

#Oreja izq
turtle.teleport(-220,195)
turtle.pencolor('black')
turtle.begin_fill()
turtle.fillcolor('gray')
turtle.circle(34)
turtle.end_fill()
#Oreja der
turtle.teleport(-30,195)
turtle.pencolor('black')
turtle.begin_fill()
turtle.fillcolor('gray')
turtle.circle(34)
turtle.end_fill()


#COHETE TRONCO
turtle.begin_fill()
turtle.fillcolor(col)
turtle.teleport(140,120)
turtle.left(30)
turtle.forward(150)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(60)
turtle.end_fill()

#COHETE SUPERIOR 
turtle.begin_fill()
turtle.fillcolor(col) 
turtle.right(120)
turtle.forward(60)
turtle.right(120)
turtle.forward(60)

#COHETE ABAJO
turtle.right(30)
turtle.forward(240)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(120)
turtle.end_fill()

#Patas
turtle.teleport(205,-120)
turtle.begin_fill()
turtle.fillcolor('Pink')
turtle.pencolor('Pink')
turtle.circle(35)
turtle.end_fill()
#Ventana
turtle.teleport(185,70)
turtle.begin_fill()
turtle.fillcolor('cyan')
turtle.pencolor('black')
turtle.circle(15)
turtle.end_fill()
#Caja de comando
turtle.begin_fill()
turtle.fillcolor('red')
turtle.teleport(-100,-100)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.end_fill()
#botones

turtle.teleport(-60,-20)
turtle.begin_fill()
turtle.fillcolor('blue')
turtle.pencolor('black')
for i in range(4):
    turtle.right(90)
    turtle.forward(20)
turtle.end_fill()
turtle.teleport(-90,-20)
turtle.begin_fill()
turtle.fillcolor('yellow')
turtle.pencolor('black')
for i in range(4):
    turtle.right(90)
    turtle.forward(20)
    
turtle.teleport(-120,-20)
turtle.begin_fill()
turtle.fillcolor('green')
turtle.pencolor('black')
for i in range(4):
    turtle.right(90)
    turtle.forward(20)
turtle.end_fill()
turtle.begin_fill()
turtle.fillcolor('red')
turtle.teleport(170,170)
turtle.circle(5)
turtle.end_fill()

#BOTAS
turtle.begin_fill()
turtle.pencolor('red')
turtle.teleport(-180,-200)
turtle.circle(30)
turtle.teleport(-30,-200)
turtle.circle(30)
turtle.teleport(0,-20)
turtle.circle(25)

turtle.teleport(-210,-70)
turtle.circle(25)
turtle.end_fill()

#PISO
turtle.begin_fill()
turtle.fillcolor('lightgreen')
turtle.pencolor('green')
turtle.teleport(-280,-200)
turtle.forward(550)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(550)
turtle.right(90)
turtle.forward(55)
turtle.end_fill()
#MONTAÑA
turtle.begin_fill()
turtle.fillcolor('lightgreen')
turtle.teleport(245,-170)
turtle.circle(75)
turtle.end_fill()
#PISO2
turtle.begin_fill()
turtle.fillcolor('lightgreen')
turtle.pencolor('green')
turtle.teleport(-280,-200)
turtle.right(90)
turtle.forward(550)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(550)
turtle.right(90)
turtle.forward(55)
turtle.end_fill()
#PREGUNTAS Y RESPUESTAS
print("¿Qué animal es el personaje principal? \n1. Zorro \n2. Serpiente \n3. Panda")
respuesta = int(input("Escriba solo el numero de la respuesta: "))
while respuesta != 3:
        respuesta = int(input("no es la respuesta correcta, intenta de nuevo. "))

print("¡Siii!, la respuesta es el panda")
turtle.clearscreen()

#PARTE 2
turtle.speed(40000000000000)
print("PARTE 2 HISTORIA")
title('PANDA ESTELAR')
print("El control de tierra le recuerda a " + nombre)
print("lo importante, darle mantenimiento a la bomba de materia oscura y mantener el curso, de esta forma la misión será exitosa, ya que la vida de billones de seres en su galaxia está en riesgo. Por lo tanto, el primer obstáculo a vencer es el cinturón de asteroides alrededor de la orbita de su planeta natal, cruzando estos podrá activar los motores de luz e iniciar el viaje estelar de " + str(edad))
print("años luz. La misión es clara, aun sí, sabe que el precio es alto, así que, de ahora en adelante se encuentra en la soledad de la inmensidad del universo…")
bgcolor('black')
teleport(-305,-106)
begin_fill()
circle (110)
fillcolor('lightgreen')
end_fill()


for x in range (0, 100):
    pencolor('pink')
    teleport(-302, 4)
    forward(95)
    left(110)
    pencolor("pink")
    left(+ 1)
    circle (62)
#COHETE
pencolor(col)
begin_fill()
fillcolor(col)
teleport(-40,30)
forward(10)
right(90)
forward(50)
right(90)
forward(10)
right(90)
forward(50)
#COHETE SUPERIOR
teleport(-35,20)
right(100)
left(120)
forward(15)
left(130)
forward(15)
end_fill()

for x in range (0, 14):
    teleport(-90, -5)
    forward(5)
    left(20)
    pencolor("blue")
    left(+ 1)
    circle (4)

#METEORITOS
for x in range (0, 20):
    teleport(200,200)
    begin_fill()
    fillcolor('cornsilk4')
    forward(55)
    left(70)
    pencolor("grey")
    left(+ 1)
    circle (65)
    end_fill()
for x in range (0, 20):
    teleport(160,-200)
    begin_fill()
    fillcolor('cornsilk4')
    forward(25)
    left(70)
    pencolor("grey")
    left(+ 1)
    circle (32)
    end_fill()
for x in range (0, 20):
    teleport(50,200)
    begin_fill()
    fillcolor('cornsilk4')
    forward(25)
    left(70)
    pencolor("grey")
    left(+ 1)
    circle (17)
    end_fill()
for x in range (0, 20):
    teleport(150,-100)
    begin_fill()
    fillcolor('cornsilk4')
    forward(25)
    left(70)
    pencolor("grey")
    left(+ 1)
    circle (13)
    end_fill()
for x in range (0, 20):
    teleport(240,-25)
    begin_fill()
    fillcolor('cornsilk4')
    forward(25)
    left(70)
    pencolor("grey")
    left(+ 1)
    circle (38)
    end_fill()
for x in range (0, 20):
    teleport(190,70)
    begin_fill()
    fillcolor('cornsilk4')
    forward(25)
    left(70)
    pencolor("grey")
    left(+ 1)
    circle (15)
    end_fill()
for x in range (0, 20):
    teleport(-50,200)
    begin_fill()
    fillcolor('cornsilk4')
    forward(25)
    left(70)
    pencolor("grey")
    left(+ 1)
    circle (22)
    end_fill()
#ESTRELLAS
for x in range (0, 30):
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-60,150)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(0,0)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(150,60) 
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-200,-100)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(90,100)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-30,120)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(0,-200)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(120,30)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-220,-290)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-250,260)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(300,-200)
#PREGUNTAS Y RESPUESTAS
print("¿A qué le tiene que dar mantenimiento el panda? \n1. A una pizzeria \n2. A un piano \n3. Al cohete \n4. A la bomba ")
respuesta = int(input("Escriba solo el numero de la respuesta: "))
while respuesta != 4:
        respuesta = int(input("no es la respuesta correcta, intenta de nuevo. "))

print("¡Correcto, el panda debe darle mantenimiento a la bomba")
turtle.clearscreen()

#PARTE 3
print("PARTE 3 HISTORIA")
title('PANDA ESTELAR')
print("Un ¼ del viaje estelar a recorrido, sin embargo, " + nombre) 
print("se mantiene firme en su misión, ahora más que nunca que su destino está a la vista, debe acabar con el agujero negro que amenaza a su galaxia. Además, hace ya bastante perdió comunicación con su planeta natal, pero la bomba que ha sido su compañera en toda su misión, la denominó “LittleFat”, esta hace que mantenga viva la esperanza y no dude nunca. Desde este punto en el espacio puede observar, la razón de todo, su hogar, las vidas, y toda la galaxia que salvará…")
bgcolor("black")
turtle.hideturtle()
speed (80000000000000)
grados = 0

teleport (-65,10)
for x in range (0, 35):
    penup ()
    goto (-65, 10)
    pendown ()
    forward (125)
    left(+0.5)
    goto (170, 75) 
    pencolor("red")   

penup()
goto (20, -12)
pendown()
for x in range (0, 200):
    forward(95)
    left(110)
    pencolor("red")
    left(grados + 1)

for x in range (0, 30):
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-110,210)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-100,0)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(200,90)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-200,-100)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(90,100)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(30,200)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(0,-200)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(120,30)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-220,-290)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-250,260)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(300,-200)

pencolor("darkblue")
teleport (-300, -200)
x = 1
for x in range (0, 310):    
        forward(5+x)
        left(91)

pencolor("darkorchid")
teleport (-300, -200)
x = 1
for x in range (0, 325):    
        forward(5+x)
        left(91)
pencolor(col)
begin_fill()
fillcolor(col)
teleport(-70,-80)
left(45)
forward(55)
right(90)
forward(22)
right(90)
forward(55)
right(90)
forward(22)
right(90)
forward(55)
teleport(-25,-47)
left(45)
left(45)
right(120)
forward(25)
right(120)
forward(25)
end_fill()
#PREGUNTAS Y RESPUESTAS
print("¿Cuál es la misión del panda? \n1. Comprar una big mac \n2. Jugar Fortnite \n3. Ir a ver entre realidad y pesadilla parte 3 \n4. Acabar con un hoyo negro ")
respuesta = int(input("Escriba solo el numero de la respuesta: "))
while respuesta != 4:
        respuesta = int(input("no es la respuesta correcta, intenta de nuevo. "))

print("¡Tal cual hermano tal cual!, la misión del panda es acabar con un hoyo negro")
turtle.clearscreen()

#PARTE 4
print("PARTE 4 HISTORIA")
title('PANDA ESTELAR')
print("Tanto tiempo, esfuerzo y sacrificio, al final dio fruto. Ha llegado a su destino, su misión está casi completa. Permanecer en la orbita del agujero negro hace que el tiempo se dilate, para el panda pasan pocos minutos, pero para la vida en su galaxia, pasa demasiado tiempo. Aprox. desde su partida, en su planeta natal pasaron 2 mil años. No hay tiempo para pensar, debe cumplir su misión, se mantiene orbitando el agujero y se despide de la bomba que lo acompañó durante tanto. La bomba es activada, y los motores de luz para huir son activados, debe escapar…")
bgcolor("black")
turtle.hideturtle()
speed (80000000000000)
hideturtle
bgcolor("black")
speed(200000)
grados = 0

teleport (-400, 0)
for x in range (0, 50):
    penup ()
    goto (-800, 0)
    pendown ()
    forward (400)
    left(+1)
    goto (800, -100) 
    pencolor("red")   

penup()
goto (-400, -500)
pendown()
for x in range (0, 170):
    forward(1200)
    left(110)
    pencolor("red")
    left(grados + 1)

pencolor('purple')
begin_fill()
fillcolor('purple')
teleport(0,0)
right(45)
forward(20)
left(90)
forward(5)
left(90)
forward(20)
left(90)
forward(5)
left(90)
forward(20)
end_fill()
teleport(0,0)
for x in range (0, 14):
    teleport(10,-10)
    forward(5)
    left(20)
    pencolor("blue")
    left(+ 1)
    circle (4)
#PREGUNTAS Y RESPUESTAS
print("¿Cuántos años han pasado en su planeta natal desde que el panda se fue? \n1. 2 horas \n2. 2,000 años \n3. Un capitulo de un show más \n4. 10 años ")
respuesta = int(input("Escriba solo el numero de la respuesta: "))
while respuesta != 2:
        respuesta = int(input("no es la respuesta correcta, intenta de nuevo. "))

print("¡Así es!, han pasado 2,000 años desde que el panda se fue")
turtle.clearscreen()

#Parte 5
print("Parte 5 Historia")
title('PANDA ESTELAR')
print("La misión es completada, ahora mismo en lo único que piensa es en las personas, en las vidas que fueron salvadas por su sacrificio, el Panda está feliz. La bomba de materia oscura explota, haciendo colapsar la singularidad del agujero negro, en un estallido colosal la nave del Panda salvador se desvanece. Mientras tanto, en su planeta los habitantes vivieron miles de generaciones hasta que el planeta murió por el tiempo. Su hogar ya no existe, sin embargo, el Panda cumplió la misión, les permitió vivir a miles de vidas, pero él, su destino se desconoce…")
bgcolor("black")
grados = 0
speed (1000000)

#ESTRELLAS
for x in range (0, 30):
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-110,210)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-100,0)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-50,-100)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-200,-100)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-300,-250)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-220,-290)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-250,260)
    forward(8)
    left(110)
    pencolor("white")
    left(+ 1)
    teleport(-200,50)
#HOYO
teleport (-50, -50)
pencolor ("red")
left(360)
for x in range (0, 50):
    penup ()
    teleport (-50, -50)
    pendown ()
    forward (900)
    left(+0.5)
    teleport (900, 500) 
    pencolor("red")   

penup()
teleport (200, -300)
pendown()
for x in range (0, 170):
    forward(700)
    left(110)
    pencolor("red")
    left(grados + 1)

pencolor("blue")
#cohete
pencolor(col)
begin_fill()
fillcolor(col)
teleport(-140,0)
forward(160)
left(90)
forward(70)
left(90)
forward(160)
left(90)
forward(70)
left(90)
forward(160)
end_fill()

pencolor('cyan')
teleport(-250,-15)
begin_fill()
fillcolor('cyan')
circle(15)
end_fill()
for x in range (0, 20):
    teleport(-120, -30)
    forward(5)
    left(20)
    pencolor("blue")
    left(+ 1)
    circle (16)

#EXPLOSIÓN
for x in range (0, 40):
    teleport(350, 50)
    circle (62)
    forward(800)
    left(110)
    speed (3000)
    pencolor("blue")
    left(+ 1)
    teleport(350, 50)
    forward(100)
    circle (62)
    forward(650)
    left(110)
    speed (3000)
    pencolor("deepskyblue")
    left(+ 1)
    teleport(350, 50)
    forward (200)
    circle (62)
    forward(400)
    left(110)
    speed (3000)
    pencolor("cyan")
    left(+ 1)
    
teleport (400,300)
right(+55)
begin_fill()
fillcolor('white')
forward(800)
left(90)
forward(600)
left(90)
forward(800)
left(90)
forward(600)
left(90)
end_fill()

teleport (400,300)
begin_fill()
fillcolor('skyblue')
forward(800)
left(90)
forward(600)
left(90)
forward(800)
left(90)
forward(600)
left(90)
end_fill()

teleport (400,300)
begin_fill()
fillcolor('cyan')
forward(800)
left(90)
forward(600)
left(90)
forward(800)
left(90)
forward(600)
left(90)
end_fill()

teleport (400,300)
begin_fill()
fillcolor('blue')
forward(800)
left(90)
forward(600)
left(90)
forward(800)
left(90)
forward(600)
left(90)
end_fill()

teleport (400,300)
begin_fill()
fillcolor('white')
forward(800)
left(90)
forward(600)
left(90)
forward(800)
left(90)
forward(600)
left(90)
end_fill()

teleport (400,300)
begin_fill()
fillcolor('black')
forward(800)
left(90)
forward(600)
left(90)
forward(800)
left(90)
forward(600)
left(90)
end_fill() 

teleport (0,0)
write ("FIN.")
penup()
turtle.hide 
teleport (-100,100)

print("Parte 5 Historia")
title('PANDA ESTELAR')
print("La misión es completada, ahora mismo en lo único que piensa es en las personas, en las vidas que fueron salvadas por su sacrificio, el Panda está feliz. La bomba de materia oscura explota, haciendo colapsar la singularidad del agujero negro, en un estallido colosal la nave del Panda salvador se desvanece. Mientras tanto, en su planeta los habitantes vivieron miles de generaciones hasta que el planeta murió por el tiempo. Su hogar ya no existe, sin embargo, el Panda cumplió la misión, les permitió vivir a miles de vidas, pero él, su destino se desconoce…")

#PREGUNTAS Y RESPUESTAS
print("¿El panda cumplió su misión? \n1. Sí \n2. No  ")
respuesta = int(input("Escriba solo el numero de la respuesta: "))
while respuesta != 1:
        respuesta = int(input("no es la respuesta correcta, intenta de nuevo. "))

print("Correcto, el panda cumplió su misión.")
turtle.clearscreen()
turtle.done

